[package]
name = "picocadrs"
version = "0.1.0"
edition = "2021"
description = "Libary foe working with picoCAD saves."
readme = "README.md"
homepage = "https://github.com/ElektroEnte/picocadrs"
repository = "https://github.com/ElektroEnte/picocadrs"
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.19.4"