[package]
name = "picocadrs"
version = "0.1.0"
edition = "2021"
description = "Libary foe working with picoCAD saves."
readme = "README.md"
homepage = "https://github.com/ElektroEnte/picocadrs"
repository = "https://github.com/ElektroEnte/picocadrs"
license = "MIT"
keywords = ["picoCAD", "pico8"]
categories = ["data-structures", "graphics", "parsing"]
exclude = []

[dependencies]
rlua = "0.19.4"